### ISSUE TITLE
merged changes to master without review

### ISSUE THREAD

**Issue by pkmcfarland** [twistmcflip/TSTools#10]
Jared,

I merged some changes without review to master. I did it so I could keep working without bothering you. The biggest change is that I changed TSTools/python/src/**timeSeries** directory name to TSTools/python/src/**tstools**

So that the package name is tstools and not timeSeries. This will undoubtedly screw up some of the stuff you did with docker, etc. Sorry :(

**Comment by jaredonline** [comment]
Just looked through the changes and left some thoughts.
