### ISSUE TITLE
error when I ran make

### ISSUE THREAD

**Issue by pkmcfarland** [twistmcflip/TSTools#8]
Hey J,

When I ran:
`make`

A bunch of stuff was running but then I got:
`=================================== ERRORS ===========================
_______ ERROR collecting tests/timeSeries/readUnrTxyz2_test.py ______________
ImportError while importing test module '/tstools/tests/timeSeries/readUnrTxyz2_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/timeSeries/readUnrTxyz2_test.py:4: in <module>
    from timeSeries import timeSeries as ts
src/timeSeries/timeSeries.py:17: in <module>
    import plotly.graph_objects as go
E   ModuleNotFoundError: No module named 'plotly'
!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!
======================== 1 error in 0.10 seconds ===========================
make: *** [test] Error 2`

Can I fix this or is it something you should do?

**Comment by jaredonline** [comment]
I should fix it I think

**Comment by jaredonline** [comment]
I've got some of the above issue fixed, but now I'm running into: 

```
ModuleNotFoundError: No module named 'nutils'
```

Do you know where I can go to install that package?

**Comment by pkmcfarland** [comment]
Dang. Sorry. That’s an NGS library. Is it in TSTools/python/lib ?

**Comment by jaredonline** [comment]
It does not appear to be. Wanna add it?

**Comment by pkmcfarland** [comment]
Will do when I get home tonight.

**Comment by pkmcfarland** [comment]
Hey brew,
Finally added nutils to TSTools/python/lib/
